public enum Response {
    ADDRECSUCCESS,
    ADDRECSUCCESSGOALCOMPLETE,
    ADDRECFAILURE,

    EDITRECSUCCESS,
    EDITRECSUCCESSGOALINCOMPLETE,
    EDITRECSUCCESSGOALCOMPLETE,
    EDITRECFAILURE,

    ADDGOALSUCCESS,
    ADDGOALFAILURE,

    EDITGOALSUCCESS,
    EDITGOALSUCCESSNOWCOMPLETE,
    EDITGOALSUCCESSNOWINCOMPLETE,
    EDITGOALFAILURE,
}
